# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Application.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ApplicationFrame = QtWidgets.QFrame(self.centralwidget)
        self.ApplicationFrame.setGeometry(QtCore.QRect(20, 80, 711, 511))
        self.ApplicationFrame.setStyleSheet("background-color:rgb(174, 194, 221)")
        self.ApplicationFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.ApplicationFrame.setObjectName("ApplicationFrame")
        
        self.label = QtWidgets.QLabel(self.ApplicationFrame)
        self.label.setGeometry(QtCore.QRect(220, 10, 341, 52))
        self.label.setObjectName("label")
        
        self.ApplicationDisplayFrame = QtWidgets.QFrame(self.ApplicationFrame)
        self.ApplicationDisplayFrame.setGeometry(QtCore.QRect(10, 70, 691, 431))
        self.ApplicationDisplayFrame.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.ApplicationDisplayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ApplicationDisplayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ApplicationDisplayFrame.setObjectName("ApplicationDisplayFrame")
        
        self.listView = QtWidgets.QListView(self.ApplicationDisplayFrame)
        self.listView.setGeometry(QtCore.QRect(5, 1, 681, 391))
        self.listView.setObjectName("listView")
        
        self.RemoveButton = QtWidgets.QPushButton(self.ApplicationDisplayFrame)
        self.RemoveButton.setGeometry(QtCore.QRect(530, 400, 75, 23))
        self.RemoveButton.setObjectName("RemoveButton")
        
        self.AddButton = QtWidgets.QPushButton(self.ApplicationDisplayFrame)
        self.AddButton.setGeometry(QtCore.QRect(610, 400, 75, 23))
        self.AddButton.setObjectName("AddButton")
        
        self.UpdateButton = QtWidgets.QPushButton(self.ApplicationDisplayFrame)
        self.UpdateButton.setGeometry(QtCore.QRect(450, 400, 75, 23))
        self.UpdateButton.setObjectName("UpdateButton")
        
        self.MenuFrame = QtWidgets.QFrame(self.centralwidget)
        self.MenuFrame.setGeometry(QtCore.QRect(10, 10, 731, 61))
        self.MenuFrame.setStyleSheet("background-color:rgb(174, 194, 221)")
        self.MenuFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.MenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MenuFrame.setLineWidth(2)
        self.MenuFrame.setObjectName("MenuFrame")
        
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.MenuFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 711, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1069, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">MY APPLICATIONS</span></p></body></html>"))
        self.RemoveButton.setText(_translate("MainWindow", "REMOVE"))
        self.AddButton.setText(_translate("MainWindow", "ADD"))
        self.UpdateButton.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton.setText(_translate("MainWindow", "Profile"))
        self.pushButton_2.setText(_translate("MainWindow", "Applications"))
        self.pushButton_3.setText(_translate("MainWindow", "Career Interests"))
        self.pushButton_4.setText(_translate("MainWindow", "Learn More"))

    def PopulatingListView(self):
        
        
        
        
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
